namespace Game.Core{
	public enum LevelLog{
		Debug,
		Info,
		Warning,
		Error,
	}
	#region Characters

	public enum ECharacterAnimationState{
		idle_down,
		idle_up,
		idle_left,
		idle_right,
		walk_down,
		walk_up,
		walk_left,
		walk_right,
		turn_down,
		turn_up,
		turn_left,
		turn_right,

	}
	public enum ECharacterMovement
	{
		WALKING,
		JUMPING
	}
	#endregion


	#region Levels
	public enum LevelName{
		pallet_town,
		pallet_town_ashs_house,
		pallet_town_ashs_house_f1,
		pallet_town_rivals_house,
		pallet_town_pokemon_lab,
		route1,
		virdian_city,
		virdian_city_house,
		virdian_city_arcade,
		virdian_city_pokemart,
		virdian_city_pokecenter,
		virdian_city_gym,
		// Route 2 Done
		route2,
		route2_npc_house,
		route2_gate,
		route2_part2,
		// Pewter City in progress
		pewter_city,
		pewter_city_pokemart,
		pewter_city_pokecenter,
		pewter_city_gym,
		pewter_city_museum,
		pewter_city_museum_f2,
		// Route 3: Done
		route3,
		cerulean_city,
		battle_scene,
		route22,
		route_22_gate,
		route_23,
		victory_map
	}
	public enum LevelGroups{
		SPAWNPOINTS,
		SCENETRIGGERS
	}
	public enum SignType{
		METAL,
		SNOWY_METAL,
		WOOD,
		SNOWY_WOOD,
		LARGE_WOOD,
		SNOWY_LARGE_WOOD,
		LARGE_METAL,
		SNOWY_LARGE_METAL,
	}
	#endregion
	#region Pokeballs
	public enum PokeballType{
		Closed,
		Open,
	}
	#endregion
	#region Npcs
	public enum NpcAppearance{
		Gardener,
		Worker,
		BugCatcher
	}
	public enum NpcMovementType{
		Static,
		Wander,
		Patrol,
		LookAround
	}
	public enum StoryNpcAppearance 
	{
		// --- Townsfolk (Non-Battlers) ---
		OldMan,
		OldWoman,
		MiddleAgedMan,
		MiddleAgedWoman,
		Youngster,    // The classic shorts-wearing boy
		Lass,         // The classic skirt-wearing girl
		Preschooler,
		FatMan,       // Classic "Technology is incredible!" guy

		// --- Professionals ---
		Nurse,        // Joy-style
		Clerk,        // Shop/Mart worker
		Scientist,    // Lab coats
		Officer,      // Jenny-style
		Doctor,
		Chef,

		// --- Trainer Archetypes ---
		Hiker,
		Camper,
		Picnicker,
		BugCatcher,
		BlackBelt,    // Martial arts
		BattleGirl,
		AceTrainer,   // Professional look
		HexManiac,    // Ghost/Psychic vibe

		// --- Story-Specific ---
		Rival,
		ProfessorOak,
		GymLeader,
		EvilTeamGrunt,
		EvilTeamAdmin,
		Champion,
		Delia
	}
	#endregion
	#region Badges
	public enum Badge
	{
		BOULDER,
		CASCADE,
		THUNDER,
		RAINBOW,
		SOUL,
		MARSH,
		VOLCANO,
		EARTH
	}
	#endregion
	#region SaveGame
	public enum SaveGame
	{
		
	}
	#endregion
	#region Pokemon
	public enum PokemonID
	{
		none,
		bulbasaur,
		ivysaur,
		venusaur,
		charmander,
		charmeleon,
		charizard,
		squirtle,
		wartortle,
		blastoise,
		caterpie,
		metapod,
		butterfree,
		weedle,
		kakuna,
		beedrill,
		pidgey,
		pidgeotto,
		pidgeot,
		rattata,
		raticate,
		spearow,
		fearow,
		ekans,
		arbok,
		pikachu,
		raichu,
		sandshrew,
		sandslash,
		nidoranf,
		nidorina,
		nidoqueen,
		nidoranm,
		nidorino,
		nidoking,
		clefairy,
		clefable,
		vulpix,
		ninetales,
		jigglypuff,
		wigglytuff,
		zubat,
		golbat,
		oddish,
		gloom,
		vileplume,
		paras,
		parasect,
		venonat,
		venomoth,
		diglett,
		dugtrio,
		meowth,
		persian,
		psyduck,
		golduck,
		mankey,
		primeape,
		growlithe,
		arcanine,
		poliwag,
		poliwhirl,
		poliwrath,
		abra,
		kadabra,
		alakazam,
		machop,
		machoke,
		machamp,
		bellsprout,
		weepinbell,
		victreebel,
		tentacool,
		tentacruel,
		geodude,
		graveler,
		golem,
		ponyta,
		rapidash,
		slowpoke,
		slowbro,
		magnemite,
		magneton,
		farfetchd,
		doduo,
		dodrio,
		seel,
		dewgong,
		grimer,
		muk,
		shellder,
		cloyster,
		gastly,
		haunter,
		gengar,
		onix,
		drowzee,
		hypno,
		krabby,
		kingler,
		voltorb,
		electrode,
		exeggcute,
		exeggutor,
		cubone,
		marowak,
		hitmonlee,
		hitmonchan,
		lickitung,
		koffing,
		weezing,
		rhyhorn,
		rhydon,
		chansey,
		tangela,
		kangaskhan,
		horsea,
		seadra,
		goldeen,
		seaking,
		staryu,
		starmie,
		mrmime,
		scyther,
		jynx,
		electabuzz,
		magmar,
		pinsir,
		tauros,
		magikarp,
		gyarados,
		lapras,
		ditto,
		eevee,
		vaporeon,
		jolteon,
		flareon,
		porygon,
		omanyte,
		omastar,
		kabuto,
		kabutops,
		aerodactyl,
		snorlax,
		articuno,
		zapdos,
		moltres,
		dratini,
		dragonair,
		dragonite,
		mewtwo,
		mew
	}
	#endregion
	#region Move
	public enum MoveID
	{
		none = 0,
		pound = 1,
		karate_chop = 2,
		double_slap = 3,
		comet_punch = 4,
		mega_punch = 5,
		pay_day = 6,
		fire_punch = 7,
		ice_punch = 8,
		thunder_punch = 9,
		scratch = 10,
		vice_grip = 11,
		guillotine = 12,
		razor_wind = 13,
		swords_dance = 14,
		cut = 15,
		gust = 16,
		wing_attack = 17,
		whirlwind = 18,
		fly = 19,
		bind = 20,
		slam = 21,
		vine_whip = 22,
		stomp = 23,
		double_kick = 24,
		mega_kick = 25,
		jump_kick = 26,
		rolling_kick = 27,
		sand_attack = 28,
		headbutt = 29,
		horn_attack = 30,
		fury_attack = 31,
		horn_drill = 32,
		tackle = 33,
		body_slam = 34,
		wrap = 35,
		take_down = 36,
		thrash = 37,
		double_edge = 38,
		tail_whip = 39,
		poison_sting = 40,
		twineedle = 41,
		pin_missile = 42,
		leer = 43,
		bite = 44,
		growl = 45,
		roar = 46,
		sing = 47,
		supersonic = 48,
		sonic_boom = 49,
		disable = 50,
		acid = 51,
		ember = 52,
		flamethrower = 53,
		mist = 54,
		water_gun = 55,
		hydro_pump = 56,
		surf = 57,
		ice_beam = 58,
		blizzard = 59,
		psybeam = 60,
		bubble_beam = 61,
		aurora_beam = 62,
		hyper_beam = 63,
		peck = 64,
		drill_peck = 65,
		submission = 66,
		low_kick = 67,
		counter = 68,
		seismic_toss = 69,
		strength = 70,
		absorb = 71,
		mega_drain = 72,
		leech_seed = 73,
		growth = 74,
		razor_leaf = 75,
		solar_beam = 76,
		poison_powder = 77,
		stun_spore = 78,
		sleep_powder = 79,
		petal_dance = 80,
		string_shot = 81,
		dragon_rage = 82,
		fire_spin = 83,
		thunder_shock = 84,
		thunderbolt = 85,
		thunder_wave = 86,
		thunder = 87,
		rock_throw = 88,
		earthquake = 89,
		fissure = 90,
		dig = 91,
		toxic = 92,
		confusion = 93,
		psychic = 94,
		hypnosis = 95,
		meditate = 96,
		agility = 97,
		quick_attack = 98,
		rage = 99,
		teleport = 100,
		night_shade = 101,
		mimic = 102,
		screech = 103,
		double_team = 104,
		recover = 105,
		harden = 106,
		minimize = 107,
		smokescreen = 108,
		confuse_ray = 109,
		withdraw = 110,
		defense_curl = 111,
		barrier = 112,
		light_screen = 113,
		haze = 114,
		reflect = 115,
		focus_energy = 116,
		bide = 117,
		metronome = 118,
		mirror_move = 119,
		self_destruct = 120,
		egg_bomb = 121,
		lick = 122,
		smog = 123,
		sludge = 124,
		bone_club = 125,
		fire_blast = 126,
		waterfall = 127,
		clamp = 128,
		swift = 129,
		skull_bash = 130,
		spike_cannon = 131,
		constrict = 132,
		amnesia = 133,
		kinesis = 134,
		soft_boiled = 135,
		high_jump_kick = 136,
		glare = 137,
		dream_eater = 138,
		poison_gas = 139,
		barrage = 140,
		leech_life = 141,
		lovely_kiss = 142,
		sky_attack = 143,
		transform = 144,
		bubble = 145,
		dizzy_punch = 146,
		spore = 147,
		flash = 148,
		psywave = 149,
		splash = 150,
		acid_armor = 151,
		crabhammer = 152,
		explosion = 153,
		fury_swipes = 154,
		bonemerang = 155,
		rest = 156,
		rock_slide = 157,
		hyper_fang = 158,
		sharpen = 159,
		conversion = 160,
		tri_attack = 161,
		super_fang = 162,
		slash = 163,
		substitute = 164,
		struggle = 165
	}
	#endregion


}